Interactive cards
US-CBP/design-system pull request #206
Opened 2024-09-23 16:38 UTC by bagrub

#### Update to add Interactive states to cards based on interactive property

2024-09-23 18:10 UTC, dgibson666 requested changes
Some significant updates needed and probably some discussion. See comments in code.

2024-09-23 18:10 UTC, dgibson666 commented on packages/web-components/src/components/cbp-card/cbp-card.scss
> +  --cbp-interactive-card-outline-focus: var(--cbp-color-white);
these are colors - you're missing the word "color" in them. Should be --cbp-interactive-card-color-outline-focus.

2024-09-23 18:10 UTC, dgibson666 commented on packages/web-components/src/components/cbp-card/cbp-card.scss
> +[data-cbp-theme=dark][theme="dark"] cbp-card:not([context=dark-inverts]):not([context=light-always]) {
why is this added? It's redundant, technically.

2024-09-23 18:10 UTC, dgibson666 commented on packages/web-components/src/components/cbp-card/cbp-card.scss
> +        display: flex;
this shouldn't be needed. display flex is for a parent and an input cannot have children. I toggled it off and didn't see any effect.

2024-09-23 18:10 UTC, dgibson666 commented on packages/web-components/src/components/cbp-card/cbp-card.stories.tsx
> +  href:{
This should be defaulted to something. If you make it a clickable card, the anchor is not interactive without an href, so it's not focusable (and you can't see focus states) and you also can't see that the body text changes color as a live link (should be fixed probably)

2024-09-23 18:10 UTC, dgibson666 commented on packages/web-components/src/components/cbp-card/cbp-card.tsx
> +                <cbp-checkbox
I think this needs a lot more thought/discussion. I don't think the component should render the checkbox because it removes control of the form element from the developer/app. Your story doesn't have an input name, which means it wouldn't be submitted in the formData(). The reason the native inputs are slotted is so frameworks can access them directly and apply other attributes/bindings, but being rendered by the component will prevent that.

2024-09-23 18:10 UTC, dgibson666 commented on packages/web-components/src/components/cbp-card/cbp-card.tsx
> +  @Prop({ reflect: true}) disabled: boolean;
you're using disabled for styling, but the anchor is still active (if an hred was provided). You need to tie that functionality together. Take a look at the cbp-link and see how it handles disabled links as well.

2024-09-23 18:15 UTC, bagrub commented on packages/web-components/src/components/cbp-card/cbp-card.scss
> +[data-cbp-theme=dark][theme="dark"] cbp-card:not([context=dark-inverts]):not([context=light-always]) {
added this so the specificy was higher than the danger hover dark mode. was having issues with the the variables loading the light mode colors in dark for that instance, Can look for other avenues if we don't want to resolve it this way

2024-09-23 18:18 UTC, bagrub commented on packages/web-components/src/components/cbp-card/cbp-card.scss
> +  --cbp-interactive-card-outline-focus: var(--cbp-color-white);
updated variable name to outline-color

2024-09-23 18:26 UTC, bagrub commented on packages/web-components/src/components/cbp-card/cbp-card.stories.tsx
> +  href:{
set the default to point to github instance of storybook (can change this if you want, just first address i could think of that would be 'internal' & added style for the color of the a tag to map to the --cbp-card-color-text driving color on component

2024-09-24 13:55 UTC, dgibson666 requested changes
Couple in-code comments, but here are my overall testing results:

Clickable:

Need to apply aria-disabled="true" (string) to the anchor when disabled=true. This will handle the cursor.

If disabled, you need to pass "disabled" down to the checkbox in the story as well. I'm on the fence if this should be done by the component...

The anchor needs flex-grow: 1. If your viewport is large enough that the text does not reach the end of the card, you can see the hover/focus outline does not stretch the full width of the card.

I don't see the background color (and text) changing on hover/focus (only active/pressed).

Checkbox variation:

It's strange how if you click anywhere in the card, the whole card gets an active style (but it's not focusable), but it doesn't toggle the checkbox unless you've clicked the label or checkbox. The user feedback isn't lining up and I think clicking anywhere in the card should toggle the checkbox. I'm ok with deferring this, however, as it might be significant and you'll have to revisit with the radio version anyway.

Since the entire card is not focusable, I don't see the focus state at all and hover is not changing the background. (related to above)

If I view a regular card and change it to the checkbox variation, the spacing changes significantly due to the checkbox. The padding or min-height should be exposed in a CSS variable, as it gets overridden for the multi-select dropdown too.

2024-09-24 13:55 UTC, dgibson666 commented on packages/web-components/src/components/cbp-card/cbp-card.scss
> +        cursor: not-allowed;
if you made the anchor aria-disabled, the cursor would not be needed here.

2024-09-24 13:55 UTC, dgibson666 commented on packages/web-components/src/components/cbp-card/cbp-card.tsx
>            <a class='cbp-card-clickable' href={this.href}>
you need to add aria-disabled="true" (string) here, if it's disabled. This will apply the cursor automatically.

2024-09-24 15:31 UTC, dgibson666 requested changes
The only issue I'm seeing now is that for the checkbox variation the heading (label) is not inverting on click/focus like the text and is super-low contrast/unreadable.

2024-09-24 17:12 UTC, dgibson666 approved these changes
looks good. Note: still needs iterating on the check/radio cards to make them entirely clickable.

2024-09-24 17:13 UTC, merged