Feature/file input
US-CBP/design-system pull request #35
Opened 2023-06-02 20:55 UTC by dgibson666

* Renamed File Upload to File Input
* Updated styles to match design specs
  * Implemented "disabled" instead of "readonly" because "readonly" on a file input is not a thing and calling something it's not can cause confusion on expected behavior. (design specs did not specify both states)
* Update code to allow for drag and drop
* Currently only support single file uploads; more discussion around the design and workflow for multiple files is needed.

2023-06-05 13:57 UTC, dannyk3941 commented
![Screen Shot 2023-06-05 at 9 54 03 AM](https://github.com/US-CBP/design-system/assets/52807859/392185d9-d7d9-49fe-986d-b63cebecaed8)

@dgibson666 build failed due to stylesheet import. Looks like the name is not the right scss file.

2023-06-05 17:03 UTC, dannyk3941 requested changes

2023-06-07 17:24 UTC, dgibson666 commented on packages/vanilla/src/sass/components/_fileinput.scss
> +  border-radius: 3px;
done.

2023-06-07 17:25 UTC, dannyk3941 approved these changes

2023-06-07 17:26 UTC, merged