Feature/menu refactor
US-CBP/design-system pull request #40
Opened 2023-06-28 20:47 UTC by dgibson666

* Renamed the component and CSS classes to "menu" - the pattern is "overflow menu".
* Rewrote the menu functionality completely
* Added menu positioning and responsive behavior
* Added story controls

There is still some commented out CSS that I'd like to discuss before this gets merged.

2023-07-11 18:04 UTC, dannyk3941 requested changes
- One issue I'm seeing is that when the menu control/button is focused, hovering the button has a different background color than the border.
- Tabbing out of the menu when it is open does not close the menu.

2023-07-11 18:04 UTC, dannyk3941 commented on packages/vanilla/src/utilities/createUniqueId.js
> +export { createUniqueID };
You can write this as `export const createUniqueID = ....` and remove line 4.

2023-07-12 15:19 UTC, dgibson666 commented on packages/vanilla/src/index.js
> +//import './sass/main.scss';
Good question. I was trying to figure out why we were importing SASS into the JS, but this makes sense I guess.

2023-07-12 15:24 UTC, dgibson666 commented on packages/vanilla/src/sass/components/_fileinput.scss
> +    border-color: var(--cbp-color-interactive-focus-darker); // TechDebt: not to spec
I'm fixing this in this branch, but the focus colors of the selected file(s) remove buttons are also off. I'm fixing those in the separate bugfix branch.

2023-07-12 15:25 UTC, dgibson666 commented on packages/vanilla/src/sass/components/_menu.scss
> +        margin-right: 8px;
done

2023-07-12 17:38 UTC, merged